Feature/enum methods
cliftondavies/Enumerable-Methods pull request #2
Opened 2020-03-26 00:37 UTC by cliftondavies

# Project: Enumerables
## Milestones
- [x] Setup files
- [x] my_each
- [x] my_each_with_index
- [x] my_select
- [x] my_all?
- [x] my_any?
- [x] my_none?
- [x] my_count
- [x] my_map
- [x] my_inject
- [x] multiply_els
- [x] my_map_with_proc
- [x] Local Rubocop
- [x] GitHub Stickler
- [x] README

2020-03-26 21:37 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @cliftondavies :balloon: 

### Good job creating all your Enumerable methods, now let's make them work properly, please address the comments I've left directly in your code :point_down: 

**Hint:** follow this [guide](https://ruby-doc.org/core-2.6.5/Enumerable.html), all the examples for each of the Enumerable methods should be able to work using your own Enumerable methods.

### That's it! :raised_hands: 

### Please :pray: do the changes :man_technologist: and submit back for a code review when you are done :memo: 

Happy Coding :rocket: 

Any questions? is better to ask me on slack **@ Maru**

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

2020-03-26 21:37 UTC, euqueme commented on enumerable.rb
> +  end
* [ ] should have working `my_each`  identical and returns the same thing as ruby's [`each`](https://ruby-doc.org/core-2.6.4/Array.html#method-i-each). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_each.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

#### my_each

- [ ] my_each calls the given block once for each element in self

Given this
```ruby
block = proc { |x| puts x + 10 }
```
when executing these commands 
```ruby
[1, 5, 2].my_each(&block) 
[1, 5, 2].each(&block) 
[1, 5, 2].my_each{ |x| puts x + 10 }  
[1, 5, 2].each{ |x| puts x + 10 } 

```
should  all return the same result

```ruby
#result
11
15
12
```

- Yours is always expecting an array as an argument
![image](https://user-images.githubusercontent.com/52209067/77674765-ac2ebe00-6f51-11ea-8ca1-d612d185e15e.png)

- Real each
![image](https://user-images.githubusercontent.com/52209067/77674848-ccf71380-6f51-11ea-8b20-4469ccefdae6.png)

- [ ] my_each returns an Enumerator if no block is given

- Yours is always expecting an array as an argument
![image](https://user-images.githubusercontent.com/52209067/77675355-75a57300-6f52-11ea-828c-060f87df5c31.png)

- Real each
![image](https://user-images.githubusercontent.com/52209067/77675424-8a820680-6f52-11ea-9013-f537927bd221.png)

2020-03-26 21:37 UTC, euqueme commented on enumerable.rb
> +  end
* [ ] should have working `my_each_with_index` identical and returns the same thing as ruby's [`each_with_index`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-each_with_index). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_each_with_index.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

#### my_each_with_index

- [ ] my_each_with_index calls the given block once for each element in self

Given this
```ruby
block = proc { |x, i| puts x + i }
```
when executing these commands 
```ruby
[1, 5, 2].my_each_with_index(&block) 
[1, 5, 2].each_with_index(&block) 
[1, 5, 2].my_each_with_index{ |x| puts x + i }  
[1, 5, 2].each_with_index{ |x| puts x + i } 
```
should  all return the same result
```ruby
#result
1
6
4
```
- Yours is always expecting an array as an argument
![image](https://user-images.githubusercontent.com/52209067/77678521-e8185200-6f56-11ea-9764-15ab1088c359.png)

- Real each_with_index
![image](https://user-images.githubusercontent.com/52209067/77679518-41cd4c00-6f58-11ea-87ab-3164a3a5829e.png)

- [ ] my_each_with_index returns an Enumerator if no block is given

- Yours is always expecting an array as an argument
![image](https://user-images.githubusercontent.com/52209067/77680114-1eef6780-6f59-11ea-8984-30002eb35881.png)

- Real each_with_index
![image](https://user-images.githubusercontent.com/52209067/77680236-4ba37f00-6f59-11ea-8423-28dfc3dbf205.png)

2020-03-26 21:37 UTC, euqueme commented on enumerable.rb
> +  end
* [ ] should have working `my_select` identical and returns the same thing as ruby's [`select`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-select). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_select.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

#### my_select

- [ ] my_select returns an array containing all elements of enum for which the given block returns a true value

```ruby
[1, 5, 2].my_select {|x| x > 2 } == [1, 5, 2].select {|x| x > 2 } => 5
```
- Yours is giving an ArgumentError
![image](https://user-images.githubusercontent.com/52209067/77681008-59a5cf80-6f5a-11ea-8f71-e4b66338449e.png)

- Real select
![image](https://user-images.githubusercontent.com/52209067/77681250-af7a7780-6f5a-11ea-8f23-c3c4366f253e.png)

- [ ] my_select returns an enumerator if no block is given

- Yours is giving an ArgumentError
![image](https://user-images.githubusercontent.com/52209067/77681430-e9e41480-6f5a-11ea-8871-3e89be0407c2.png)

- Real select
![image](https://user-images.githubusercontent.com/52209067/77681510-0bdd9700-6f5b-11ea-9340-ac116b7ed62e.png)

2020-03-26 21:37 UTC, euqueme commented on enumerable.rb
> +  end
* [ ] should have working `my_all?`  identical and returns the same thing as ruby's [`all?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-all-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_all.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

#### my_all? 

- [ ] when no block or argument is given returns true only when none of the collection members are false or nil if the mentioned condition is not met it should return false

```ruby     
[nil, false, true, []].my_all? == [nil, false, true, []].all? => false
```
- Yours is giving ArgumentError
![image](https://user-images.githubusercontent.com/52209067/77688238-595f0180-6f65-11ea-98ac-141da99297e1.png)

- Real all?
![image](https://user-images.githubusercontent.com/52209067/77688266-67148700-6f65-11ea-82e5-cbef16444817.png)

- [ ] when a class is passed as an argument returns true only if all of the collection is a member of such class, otherwise, it should return false

```ruby     
[1, 2.5, 'a', 9].my_all?(Integer) == [1, 2.5, 'a', 9].all?(Integer) => false
```
- Yours is retrieving a NoMethodError
![image](https://user-images.githubusercontent.com/52209067/77688408-a8a53200-6f65-11ea-9886-f108515baa5f.png)

- Real all?
![image](https://user-images.githubusercontent.com/52209067/77688467-be1a5c00-6f65-11ea-8970-15c9e4f4913f.png)

- [ ] when a Regex is passed as an argument returns true if all of the collection matches the Regex

```ruby     
%w[dog door rod blade].my_all?(/d/) == %w[dog door rod blade].all?(/d/) => true
```
- Yours is retrieving a NoMethodError
![image](https://user-images.githubusercontent.com/52209067/77688653-10f41380-6f66-11ea-8090-1c933aac0df6.png)

- Real all?
![image](https://user-images.githubusercontent.com/52209067/77688741-31bc6900-6f66-11ea-90ec-b6a7cee7e6ca.png)

- [ ] when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

```ruby     
[3,4,7,11].my_all?(3) == [3,4,7,11].all?(3)  => false 
```
- Yours is retrieving a NoMethodError
![image](https://user-images.githubusercontent.com/52209067/77688960-7ea03f80-6f66-11ea-9895-15682455f8fc.png)

- Real all?
![image](https://user-images.githubusercontent.com/52209067/77689001-924ba600-6f66-11ea-9b72-210b3bb1d78b.png)

2020-03-26 21:37 UTC, euqueme commented on enumerable.rb
> +  end
- [ ] should have working `my_any?` identical and returns the same thing as ruby's [`any?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-any-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_any.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

 #### my_any? 

- [ ] when no block or argument is given returns true if at least one of the collection is not false or nil

```ruby     
[nil, false, true, []].my_any? == [nil, false, true, []].any? => true
```
- Yours returns an ArgumentError
![image](https://user-images.githubusercontent.com/52209067/77689397-31709d80-6f67-11ea-8762-a2c98c02214c.png)

- Real any?
![image](https://user-images.githubusercontent.com/52209067/77689425-3f262300-6f67-11ea-88a9-2885ebab08d4.png)

- [ ] when a class is passed as an argument returns true if at least one of the collection is a member of such class

```ruby
[1, 2.5, 'a', 9].my_any?(Integer) == [1, 2.5, 'a', 9].any?(Integer) => true
```
- Yours is retrieving a NoMethodError
![image](https://user-images.githubusercontent.com/52209067/77689571-7dbbdd80-6f67-11ea-9d07-6c81c9bc2915.png)

- Real any?
![image](https://user-images.githubusercontent.com/52209067/77689595-8f04ea00-6f67-11ea-9f51-4536c3f8049b.png)

- [ ] when a Regex is passed as an argument returns false if none of the collection matches the Regex

```ruby
%w[dog door rod blade].my_any?(/z/) == %w[dog door rod blade].any?(/z/) => false
```
- Yours retrieves a NoMethodError
![image](https://user-images.githubusercontent.com/52209067/77689711-beb3f200-6f67-11ea-934a-7a0a918e0455.png)

- Real any?
![image](https://user-images.githubusercontent.com/52209067/77689742-cf646800-6f67-11ea-9e3e-eec7a960fe38.png)

- [ ] when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern

```ruby
[3,4,7,11].my_any?(3) should be equal to this [3,4,7,11].any?(3) => true
```
- Yours retrieves a NoMethodError
![image](https://user-images.githubusercontent.com/52209067/77689843-00449d00-6f68-11ea-87a8-da469331d92a.png)

- Real any?
![image](https://user-images.githubusercontent.com/52209067/77689883-10f51300-6f68-11ea-8a4c-319977bb3842.png)

2020-03-26 21:37 UTC, euqueme commented on enumerable.rb
> +  end
- [ ] should have working `my_none?` identical and returns the same thing as ruby's [`none?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-none-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_none.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

#### my_none?

- [ ] when no block or argument is given returns true only if none of the collection members is true
```ruby
[nil, false, true, []].my_none? == [nil, false, true, []].none? => false
```
- Yours is retrieving an ArgumentError
![image](https://user-images.githubusercontent.com/52209067/77690309-b60feb80-6f68-11ea-8424-8fc0e6b3fc59.png)

- Real none?
![image](https://user-images.githubusercontent.com/52209067/77690365-cd4ed900-6f68-11ea-9933-f73b0091208d.png)

- [ ] when a class is passed as an argument returns true if none of the collection is a member of such class
```ruby
[1, 2.5, 'a', 9].my_none?(Integer) == [1, 2.5, 'a', 9].none?(Integer) => false
```
- Yours is retrieving a NoMethodError
![image](https://user-images.githubusercontent.com/52209067/77690513-05eeb280-6f69-11ea-8535-9343ab8052ea.png)

- Real none?
![image](https://user-images.githubusercontent.com/52209067/77690539-130ba180-6f69-11ea-8bd0-6ca061ab05d2.png)

- [ ] when a Regex is passed as an argument returns true only if none of the collection matches the Regex
```ruby
%w[dog door rod blade].my_none?(/z/) == %w[dog door rod blade].none?(/z/) => true
```
- Yours is retrieving a NoMethodError
![image](https://user-images.githubusercontent.com/52209067/77690678-4d753e80-6f69-11ea-992d-1b0db59e2b3c.png)

- Real none?
![image](https://user-images.githubusercontent.com/52209067/77690722-65e55900-6f69-11ea-8881-9afe27d263dc.png)

- [ ] when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
```ruby
[3,4,7,11].my_none?(3) == [3,4,7,11].none?(3) => false
```
- Yours is retrieving a NoMethodError
![image](https://user-images.githubusercontent.com/52209067/77690884-9c22d880-6f69-11ea-9bbd-f0eddc09c7e2.png)

- Real none?
![image](https://user-images.githubusercontent.com/52209067/77690915-a9d85e00-6f69-11ea-81b3-7adb07b281ca.png)

[OPTIONAL]

I think we could get the block of my_none? from my_any? we should only do something like !my_any? for my_none? to work. For example:

  def my_none?(arg = nil, &block)
    !my_any?(arg = nil,&block)
  end

To make this work we have to use block.call(element) instead of yield(element) in my_any?

2020-03-26 21:37 UTC, euqueme commented on enumerable.rb
> +  end
- [ ] should have working `my_count` identical and returns the same thing as ruby's [`count`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-count). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_count.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

2020-03-26 21:37 UTC, euqueme commented on enumerable.rb
> +  end
* [ ] should have working `my_count` identical and returns the same thing as ruby's [`count`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-count). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_count.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

#### my_count

- [ ] my_count returns the number of items in enum through enumeration
```ruby
[5, 4, 1].my_count == [5, 4, 1].count => 3
```
- Yours is giving an ArgumentError
![image](https://user-images.githubusercontent.com/52209067/77696262-b4e3bc00-6f72-11ea-9cbe-75dc178d2de8.png)

- Real count
![image](https://user-images.githubusercontent.com/52209067/77696292-c200ab00-6f72-11ea-8e97-5a2b79256cbc.png)

- [ ] my_count counts the number of items in enum that are equal to the item if an argument is given
```ruby
[5, 4, 1].my_count(4) == [5, 4, 1].count(4) => 1
```
- Yours is giving an NoMethodError
![image](https://user-images.githubusercontent.com/52209067/77696347-d6dd3e80-6f72-11ea-8b7e-60078c7c0085.png)

- Real count
![image](https://user-images.githubusercontent.com/52209067/77696378-e2306a00-6f72-11ea-9310-0bb30ab9c94d.png)

- [ ] my_count counts the number of elements yielding a true value if a block is given
```ruby
[5, 4, 1].my_count { |x| x > 2 } == [5, 4, 1].count { |x| x > 2 }
```
- Yours is giving an ArgumentError
![image](https://user-images.githubusercontent.com/52209067/77696427-faa08480-6f72-11ea-8113-b3fbc2fd1a81.png)

- Real count
![image](https://user-images.githubusercontent.com/52209067/77696440-055b1980-6f73-11ea-9b41-09dac295d3d3.png)

2020-03-26 21:37 UTC, euqueme commented on enumerable.rb
> +  end
* [ ] should have working `my_map` identical and returns the same thing as ruby's [`map`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-map). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_map.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

#### my_map 

- [ ] given a block returns a new array with the results of running the block once for every element in enum.
```ruby
[2,4,7,11].my_map {|num| num < 10 } == [2,4,7,11].map {|num| num < 10 
```
- Yours is retrieving an ArgumentError
![image](https://user-images.githubusercontent.com/52209067/77697412-70592000-6f74-11ea-80b1-c9ff3f5bfa63.png)
- Real map
![image](https://user-images.githubusercontent.com/52209067/77697467-85ce4a00-6f74-11ea-9650-70790cae2000.png)

- [ ] returns an Enumerator if no block is given
```ruby
[2,4,7,11].my_map should be equal to [2,4,7,11].map #<Enumerator: [2, 4, 7, 11]:map
```
- Yours is retrieving an ArgumentError
![image](https://user-images.githubusercontent.com/52209067/77697596-c4640480-6f74-11ea-9488-1b55b82f2aa4.png)
- Real map
![image](https://user-images.githubusercontent.com/52209067/77697646-dc3b8880-6f74-11ea-9277-4ed4a2b3af4c.png)

- [ ] in the specifications of the project in the [Odin project](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks) # 12, you were asked to modify your my_map method to take either a proc or a block. And if both a proc and a block are given, only execute the proc. The real map doesn't have this feature, but you were asked to have it so let's work on it

Given 
```ruby
my_proc = Proc.new {|num| num > 10 }
```
Result
```ruby
puts [18, 22, 5, 6] .my_map(my_proc) {|num| num < 10 }  => true true false false
```

2020-03-26 21:37 UTC, euqueme commented on enumerable.rb
> +  end
- [ ] should have working `my_inject` **(covered by automated tests)** identical and returns the same thing as ruby's [`inject`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-inject). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_inject.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

####  my_inject

- [ ] combines all elements of enum by applying a binary operation, specified by a block
```ruby
(1..5).my_inject(4) { |prod, n| prod * n } ==l (1..5).inject(4) { |prod, n| prod * n } => 480
```
- Yours is retrieving a NoMethodError
![image](https://user-images.githubusercontent.com/52209067/77698374-1eb19500-6f76-11ea-8b2c-5d532302ce65.png)

- Real inject
![image](https://user-images.githubusercontent.com/52209067/77698409-2ffaa180-6f76-11ea-91d3-9778aa560411.png)

- [ ] When a symbol is provided as an argument, my_inject should combine the elements of the enum using that symbol as a named method.
```ruby
[2, 5, 6].my_inject(:+) == [2, 5, 6].inject(:+) => 13
```
- Yours is retrieving a NoMethodError
![image](https://user-images.githubusercontent.com/52209067/77698501-56b8d800-6f76-11ea-937a-975824cfa279.png)

- Real inject
![image](https://user-images.githubusercontent.com/52209067/77698534-6a643e80-6f76-11ea-9d0e-ebb0f02da179.png)

2020-03-26 21:37 UTC, euqueme commented on enumerable.rb
> +end
- [ ] multipy_els is not an enumerable method so let's take it out of the Enumerable module

2020-03-26 21:37 UTC, euqueme commented on enumerable.rb
> +end
- [ ] your my_map method should be able to take a proc no need to create a different method for it

2020-03-31 00:52 UTC, cliftondavies commented
#### :wave: :wave: @euqueme 

#### Thank you for the very detailed review! :pray: You're a :star2: :raised_hands: 

#### I have implemented all requested changes. :memo: 

Happy Coding! :woman_technologist: :rocket:

2020-03-31 02:05 UTC, majovanilla requested changes
Hey @cliftondavies , 👋

## You did a *great* job on this project! 💜 And you are almost done!!

There are still some changes 👇 you need to implement to approve this request 🔍

Check comments below :point_down: 

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-03-31 02:05 UTC, majovanilla commented on enumerable.rb
> +        arr.shift
Check my_inject when applying a binary operation using a block `{|e, acc| e + acc} ` It's not returning the right number.

You are not considering the case for when the user passes a symbol as an operator. `[1,2,3,4].my_inject(:+)`

2020-03-31 12:00 UTC, cliftondavies commented
### Hey @majovanilla. Thanks for the review 👍 🙏 

### I re-ran tests for each of the test cases for my_inject, and they all checked out. ✔️ 

### The checks are listed below:

### Passing only a symbol as an operator
`(5..10).my_inject(:+)                             # => 45`
`[2, 5, 6].my_inject(:*)                    # => 60`
`[2, 5, 6].my_inject(:-)                    # => -9`
`[1,2,3,4].my_inject(:+)      # => 10`

### Passing an initial value and a symbol
 `(5..10).my_inject(1, :*)                          # => 151200`

### Applying a binary operation using a block
`[1,2,3,4].my_inject { |e, acc| e + acc }    # => 10`
`(5..10).my_inject { |sum, n| sum + n }            # => 45`

### Passing an initial value with a block
`(1..5).my_inject(4) { |prod, n| prod * n }   # => 480`
`(5..10).my_inject(1) { |product, n| product * n }   # => 151200`

### Bonus: Finding the longest word with a block
```
longest = %w{ cat sheep bear }.my_inject do |memo, word|
   memo.length > word.length ? memo : word
end
```    # => "sheep"

2020-03-31 20:00 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @cliftondavies :handshake: 

### You've done a great job and almost all your Enumerable methods work but there are some changes to be made for them to run in every Operating System please do these changes :point_down: 

#### require_relative

- [ ] I have trouble running the test cases and loading the IRB with your Enumerable methods because of the pattern.rb file is not required in your enumerable.rb file so please require it at the beginning like this:

```ruby
require_relative 'pattern'
module Enumerable
 include Pattern
  def my_each
.
.
  end
.
.
end
```

- These were the errors I got before correcting the line:
![image](https://user-images.githubusercontent.com/52209067/78033088-2af57380-7323-11ea-9813-7986c5bada14.png)

#### my_all?, my_any? and pattern.rb

- [ ] I have left comments in your code with the changes I had to make to be able to execute your Pattern module methods within your Enumerable module in Ubuntu, please also change them in your code as most of the reviewers use Linux to review and it'll be easier to run your methods also whoever wants to download or clone your repo would also be able to run your methods without a problem.

#### my_inject

Your my_inject method still retrieves the wrong answer like it was pointed out by @majovanilla for these cases so let's make them work

- [ ] combines all elements of enum by applying a binary operation, specified by a block
```ruby
#Given
array = Array.new(100) { rand(0...9)}
pr = proc { |sum, n| sum + n }

array.my_inject(&pr) == array.inject(&pr) 
```
- Yours is retrieving the wrong answer (always more than it should)
![image](https://user-images.githubusercontent.com/52209067/78068328-71fc5c80-7355-11ea-8b45-4738a8a7117d.png)

- Real inject
![image](https://user-images.githubusercontent.com/52209067/78068354-7d4f8800-7355-11ea-84c2-9a840827782b.png)

- [ ] When a symbol is provided as an argument, my_inject should combine the elements of the enum using that symbol as a named method.
```ruby
#Given
array = Array.new(100) { rand(0...9)}
array.my_inject(:+) == array.inject(:+)
```
- Yours is retrieving the wrong answer (always more than it should)
![image](https://user-images.githubusercontent.com/52209067/78068846-63627500-7356-11ea-8573-10af7e7d16ad.png)

- Real inject
![image](https://user-images.githubusercontent.com/52209067/78068877-707f6400-7356-11ea-9536-0de1fb979130.png)

### multiply_els

- [ ] in my first review, I told you to take this method out of the Enumerable module but you deleted it, please include it in your project in another module (it could be in your enumerable.rb file as long as it's in another module)

### That's it! :raised_hands: 

### Please :pray: make the changes :man_technologist:  and submit back for a code review when you are done :woman_technologist: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru**

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-03-31 20:00 UTC, euqueme commented on enumerable.rb
> +      result = my_all_pattern?(pattern)
- [ ] change line 34 with the next line:
```ruby
result = Pattern.my_all_pattern?(self, pattern)
```

2020-03-31 20:00 UTC, euqueme commented on enumerable.rb
> +      result = my_any_pattern?(pattern)
- [ ] Change line 47 with the next line:

```ruby
result = Pattern.my_any_pattern?(self,pattern)
```

2020-03-31 20:00 UTC, euqueme commented on pattern.rb
> +  def my_all_pattern?(pattern)
- [ ] Change line 2 so it takes another argument and the my_all changes work properly:

```ruby
def self.my_all_pattern?(enum,pattern)
```

2020-03-31 20:00 UTC, euqueme commented on pattern.rb
> +      to_a.my_each { |item| result = false unless item == pattern }
- [ ] Change lines 6, 8 and 10 with these lines:

```ruby
     enum.to_a.my_each { |item| result = false unless item.is_a?(pattern) }   
     enum.to_a.my_each { |item| result = false unless item.match(pattern) }
     enum.to_a.my_each { |item| result = false unless item == pattern }
```

2020-03-31 20:00 UTC, euqueme commented on pattern.rb
> +  def my_any_pattern?(pattern)
- [ ] change line 15 so the my_any changes work properly:

```ruby
def self.my_any_pattern?(enum,pattern)
```

2020-03-31 20:00 UTC, euqueme commented on pattern.rb
> +      to_a.my_each { |item| result = true if item == pattern }
- [ ] change lines 19, 21 and 23 with these lines:

```ruby
      enum.to_a.my_each { |item| result = true if item.is_a?(pattern) }
      enum.to_a.my_each { |item| result = true if item.match(pattern) }
      enum.to_a.my_each { |item| result = true if item == pattern }
```

2020-04-02 14:55 UTC, cliftondavies commented
### Thanks again, @euqueme. :pray: 

### All **Requested Changes** have been implemented.

2020-04-02 22:51 UTC, euqueme approved these changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @cliftondavies :handshake: 

### You've done an amazing job with this project :star:  Thank you for doing all the suggested changes :medal_sports:  you should feel very proud of yourself, everything checks so please merge this branch and continue :tada: :tada: :tada: 

PROJECT STATUS: APPROVED :heavy_check_mark:

2020-04-02 22:58 UTC, cliftondavies commented
### Thank YOU! @euqueme 🙏 ⭐️

2020-04-02 22:58 UTC, merged